apiVersion: v1
kind: ServiceAccount
metadata:
  name: favnir-compiler-sa
  namespace: favnir-demo
  annotations:
    eks.amazonaws.com/role-arn: COMPILER_ROLE_ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: favnir-executor-sa
  namespace: favnir-demo
  annotations:
    eks.amazonaws.com/role-arn: EXECUTOR_ROLE_ARN
