# Generated by fav transpile --target python
# Source: ../infra/e2e-demo/fav2py/src/pipeline.fav
from __future__ import annotations
from dataclasses import dataclass, asdict
from typing import List, Optional, Any
import sys
import csv as _csv_mod
import io as _io_mod
import json as _json_mod
import boto3
import psycopg2
import psycopg2.extras
import os as _os
import secrets

class Ok:
    def __init__(self, value): self.value = value
class Err:
    def __init__(self, error): self.error = error

@dataclass
class TxnRow:
    id: int
    region: str
    category: str
    amount: float

@dataclass
class SummaryRow:
    region: str
    category: str
    total: float
    count: int

_SCHEMA_REGISTRY = {
    "TxnRow": TxnRow,
    "SummaryRow": SummaryRow,
}

def _io_read_file_raw(path: str):
    try:
        with open(path, encoding='utf-8') as _f:
            return Ok(_f.read())
    except Exception as _e:
        return Err(str(_e))

def _io_write_file_raw(path: str, text: str):
    try:
        with open(path, 'w', encoding='utf-8') as _f:
            _f.write(text)
        return Ok(None)
    except Exception as _e:
        return Err(str(_e))

def _csv_parse_raw(text: str, sep: str, has_header: bool):
    try:
        _r = _csv_mod.DictReader(_io_mod.StringIO(text), delimiter=sep)
        import json as _j; return Ok(_j.dumps([dict(_row) for _row in _r]))
    except Exception as _e:
        return Err(str(_e))

def _aws_s3_put_object_raw(bucket: str, key: str, body: str):
    try:
        boto3.client("s3").put_object(Bucket=bucket, Key=key, Body=body.encode("utf-8"))
        return Ok(None)
    except Exception as _e:
        return Err(str(_e))

def _aws_s3_get_object_raw(bucket: str, key: str):
    try:
        _body = boto3.client("s3").get_object(Bucket=bucket, Key=key)["Body"].read().decode("utf-8")
        return Ok(_body)
    except Exception as _e:
        return Err(str(_e))

def _aws_s3_list_objects_raw(bucket: str, prefix: str):
    try:
        _resp = boto3.client("s3").list_objects_v2(Bucket=bucket, Prefix=prefix)
        return Ok([_o["Key"] for _o in _resp.get("Contents", [])])
    except Exception as _e:
        return Err(str(_e))

def _aws_s3_delete_object_raw(bucket: str, key: str):
    try:
        boto3.client("s3").delete_object(Bucket=bucket, Key=key)
        return Ok(None)
    except Exception as _e:
        return Err(str(_e))

def _aws_s3_head_bucket_raw(bucket: str):
    try:
        boto3.client("s3").head_bucket(Bucket=bucket)
        return Ok(None)
    except Exception as _e:
        return Err(str(_e))

def _aws_s3_get_object_base64_raw(bucket: str, key: str):
    try:
        _data = boto3.client("s3").get_object(Bucket=bucket, Key=key)["Body"].read()
        return Ok(_base64_mod.b64encode(_data).decode("utf-8"))
    except Exception as _e:
        return Err(str(_e))

def _aws_s3_put_bytes_raw(bucket: str, key: str, body_list):
    try:
        boto3.client("s3").put_object(Bucket=bucket, Key=key, Body=bytes(body_list))
        return Ok(None)
    except Exception as _e:
        return Err(str(_e))

def _pg_connect():
    _url = _os.environ.get("DATABASE_URL")
    if _url:
        return psycopg2.connect(_url)
    return psycopg2.connect(
        host=_os.environ.get("PGHOST", "localhost"),
        port=int(_os.environ.get("PGPORT", "5432")),
        dbname=_os.environ.get("PGDATABASE", "postgres"),
        user=_os.environ.get("PGUSER", "postgres"),
        password=_os.environ.get("PGPASSWORD", ""),
    )

def _pg_adapt(_sql, _params_json):
    import re as _re
    _sql_py = _re.sub(r'\$\d+', '%s', _sql)
    _raw = _json_mod.loads(_params_json) if isinstance(_params_json, str) else _params_json
    _ps = [_json_mod.dumps(_p) if isinstance(_p, (list, dict)) else _p for _p in _raw]
    return _sql_py, _ps

def _pg_execute(_sql, _params_json):
    _sql_py, _ps = _pg_adapt(_sql, _params_json)
    _conn = _pg_connect()
    try:
        with _conn.cursor() as _cur:
            _cur.execute(_sql_py, _ps)
        _conn.commit()
        return Ok(None)
    except Exception as _e:
        _conn.rollback()
        return Err(str(_e))
    finally:
        _conn.close()

def _pg_query(_sql, _params_json):
    _sql_py, _ps = _pg_adapt(_sql, _params_json)
    _conn = _pg_connect()
    try:
        with _conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as _cur:
            _cur.execute(_sql_py, _ps)
            _rows = [dict(_r) for _r in _cur.fetchall()]
        return Ok(_json_mod.dumps(_rows, default=float))
    except Exception as _e:
        return Err(str(_e))
    finally:
        _conn.close()

def get_csv_path(args: List[str]) -> str:
    def _match_0():
        _m0 = (args[0] if args else None)
        if _m0 is not None:
            p = _m0
            return p
        elif _m0 is None:
            return "/app/sample.csv"
        else:
            return None

    return _match_0()

# effects: IO, Postgres
def load_and_insert(path: str) -> int:
    csv_res = _io_read_file_raw(path)
    def _match_1():
        _m1 = csv_res
        if isinstance(_m1, Err):
            return "[]"
        elif isinstance(_m1, Ok):
            text = _m1.value
            def _match_2():
                _m2 = _csv_parse_raw(text, ",", True)
                if isinstance(_m2, Err):
                    return "[]"
                elif isinstance(_m2, Ok):
                    json = _m2.value
                    return json
                else:
                    return None

            return _match_2()
        else:
            return None

    rows_json = _match_1()
    _pg_execute("CREATE TABLE IF NOT EXISTS txn (id INT, region TEXT, category TEXT, amount FLOAT)", "[]")
    _pg_execute("DELETE FROM txn", "[]")
    _pg_execute("INSERT INTO txn(id,region,category,amount) SELECT (r->>'id')::int, r->>'region', r->>'category', (r->>'amount')::float FROM json_array_elements($1::json) AS r", "[" + str(rows_json) + "]")
    print("[INFO] LoadAndInsert complete")
    return 0

# effects: Postgres
def aggregate(n: int) -> str:
    def _match_3():
        _m3 = _pg_query("SELECT region, category, SUM(amount) AS total, COUNT(*)::int AS count FROM txn GROUP BY region, category ORDER BY region, category", "[]")
        if isinstance(_m3, Ok):
            json = _m3.value
            return json
        elif isinstance(_m3, Err):
            e = _m3.error
            return "[]"
        else:
            return None

    return _match_3()

# effects: IO, AWS
def save_result(result_json: str) -> None:
    uid = secrets.token_hex(10)
    print("[INFO] Saving to S3: proof/fav2py/" + str(uid) + ".json")
    def _match_4():
        _m4 = _aws_s3_put_object_raw("favnir-e2e-demo", "proof/fav2py/" + str(uid) + ".json", result_json)
        if isinstance(_m4, Ok):
            return print("[INFO] Saved to S3 successfully")
        elif isinstance(_m4, Err):
            e = _m4.error
            return print("[ERROR] S3 failed: " + str(e))
        else:
            return None

    return _match_4()

def pipeline(x):
    return save_result(aggregate(load_and_insert(x)))

# effects: IO, Postgres, AWS
def main() -> None:
    args = sys.argv[1:]
    return pipeline(get_csv_path(args))

if __name__ == "__main__":
    main()

