//! Fav AST → Python ソースコード生成 (v11.1.0)
//!
//! `fav transpile --target python <file.fav>` の出力バックエンド。
//! v11.1.0 スコープ: 型定義 / fn / bind 脱糖 / match(Option+Result) / 基本 stdlib

use crate::frontend::parser::Parser;
use crate::ast::{
    self, BinOp, Block, Effect, Expr, FnDef, FStringPart, Lit, MatchArm, Pattern, Program, Stmt,
    TypeBody, TypeDef, TypeExpr,
};

// ── Emitter ────────────────────────────────────────────────────────────────────

pub struct Emitter {
    indent: usize,
    buf: String,
    ctr: usize, // helper 関数の連番
}

impl Emitter {
    pub fn new() -> Self {
        Self {
            indent: 0,
            buf: String::new(),
            ctr: 0,
        }
    }

    fn next_id(&mut self) -> usize {
        let id = self.ctr;
        self.ctr += 1;
        id
    }

    fn ind(&self) -> String {
        "    ".repeat(self.indent)
    }

    fn line(&mut self, s: &str) {
        let ind = self.ind();
        self.buf.push_str(&format!("{}{}\n", ind, s));
    }

    fn blank(&mut self) {
        self.buf.push('\n');
    }
}

// ── Public API ─────────────────────────────────────────────────────────────────

/// Program → Python ソース文字列
pub fn emit_python(prog: &Program, source_path: &str) -> String {
    let mut e = Emitter::new();
    e.emit_program(prog, source_path)
}

/// テスト用: Fav ソース文字列から直接 Python を生成
pub fn emit_python_str(fav_src: &str) -> String {
    let prog = Parser::parse_str(fav_src, "<test>").expect("parse failed in emit_python_str");
    emit_python(&prog, "<test>")
}

// ── Program ────────────────────────────────────────────────────────────────────

impl Emitter {
    fn emit_program(&mut self, prog: &Program, source_path: &str) -> String {
        self.emit_prelude(source_path);
        for item in &prog.items {
            match item {
                ast::Item::TypeDef(td) => self.emit_type_def(td),
                ast::Item::FnDef(fd) => self.emit_fn_def(fd),
                // stage / seq は v11.2.0 で対応
                ast::Item::TrfDef(td) => {
                    self.line(&format!("# TODO: stage {} — transpile support in v11.2.0", td.name));
                    self.blank();
                }
                ast::Item::FlwDef(fd) => {
                    self.line(&format!("# TODO: seq {} — transpile support in v11.2.0", fd.name));
                    self.blank();
                }
                // import / use / interface 等は無視
                _ => {}
            }
        }
        self.buf.clone()
    }

    fn emit_prelude(&mut self, source_path: &str) {
        self.line("# Generated by fav transpile --target python");
        self.line(&format!("# Source: {}", source_path));
        self.line("from __future__ import annotations");
        self.line("from dataclasses import dataclass, asdict");
        self.line("from typing import List, Optional, Any");
        self.line("import sys");
        self.blank();
        self.line("class Ok:");
        self.indent += 1;
        self.line("def __init__(self, value): self.value = value");
        self.indent -= 1;
        self.line("class Err:");
        self.indent += 1;
        self.line("def __init__(self, error): self.error = error");
        self.indent -= 1;
        self.blank();
    }
}

// ── TypeDef ─────────────────────────────────────────────────────────────────────

impl Emitter {
    fn emit_type_def(&mut self, td: &TypeDef) {
        match &td.body {
            TypeBody::Record(fields) => {
                self.line("@dataclass");
                self.line(&format!("class {}:", td.name));
                self.indent += 1;
                if fields.is_empty() {
                    self.line("pass");
                } else {
                    for f in fields {
                        let py_ty = map_type(&f.ty);
                        self.line(&format!("{}: {}", f.name, py_ty));
                    }
                }
                self.indent -= 1;
                self.blank();
            }
            TypeBody::Sum(_) | TypeBody::Alias(_) | TypeBody::Wrapper(_) => {
                self.line(&format!(
                    "# TODO: type {} (sum/alias/wrapper) — not yet supported",
                    td.name
                ));
                self.blank();
            }
        }
    }
}

// ── 型マッピング ───────────────────────────────────────────────────────────────

fn map_type(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Named(name, args, _) => match name.as_str() {
            "String" => "str".to_string(),
            "Int" => "int".to_string(),
            "Float" => "float".to_string(),
            "Bool" => "bool".to_string(),
            "Unit" => "None".to_string(),
            "List" => {
                let inner = args.first().map(map_type).unwrap_or_else(|| "Any".to_string());
                format!("List[{}]", inner)
            }
            "Option" => {
                let inner = args.first().map(map_type).unwrap_or_else(|| "Any".to_string());
                format!("Optional[{}]", inner)
            }
            "Result" => "Any".to_string(), // Ok/Err ヘルパークラスを使用
            other => other.to_string(),
        },
        TypeExpr::Optional(inner, _) => format!("Optional[{}]", map_type(inner)),
        TypeExpr::Fallible(inner, _) => format!("Any  # fallible {}", map_type(inner)),
        TypeExpr::Arrow(_, _, _) | TypeExpr::TrfFn { .. } => "Any".to_string(),
    }
}

fn map_effect(e: &Effect) -> &'static str {
    match e {
        Effect::Io => "IO",
        Effect::Db | Effect::DbRead | Effect::DbWrite | Effect::DbAdmin => "DB",
        Effect::Network => "Network",
        Effect::Http => "Http",
        Effect::Llm => "Llm",
        Effect::Snowflake => "Snowflake",
        Effect::Rpc => "Rpc",
        Effect::File => "File",
        Effect::Unknown(_) => "Unknown",
        _ => "Effect",
    }
}

// ── FnDef ─────────────────────────────────────────────────────────────────────

impl Emitter {
    fn emit_fn_def(&mut self, fd: &FnDef) {
        // エフェクトコメント
        if !fd.effects.is_empty() {
            let eff_strs: Vec<&str> = fd.effects.iter().map(|e| {
                if let Effect::Unknown(s) = e { return s.as_str(); }
                map_effect(e)
            }).collect();
            self.line(&format!("# effects: {}", eff_strs.join(", ")));
        }
        // def シグネチャ
        let params: Vec<String> = fd
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, map_type(&p.ty)))
            .collect();
        let ret_ty = fd
            .return_ty
            .as_ref()
            .map(map_type)
            .unwrap_or_else(|| "None".to_string());
        self.line(&format!(
            "def {}({}) -> {}:",
            fd.name,
            params.join(", "),
            ret_ty
        ));
        self.indent += 1;
        self.emit_block_body(&fd.body);
        self.indent -= 1;
        self.blank();
    }

    /// ブロックをステートメント列 + return で出力
    fn emit_block_body(&mut self, block: &Block) {
        if block.stmts.is_empty() {
            // 末尾式のみ
            let ret = self.emit_expr(&block.expr);
            self.line(&format!("return {}", ret));
            return;
        }
        for stmt in &block.stmts {
            self.emit_stmt(stmt);
        }
        // ブロック末尾の式
        match block.expr.as_ref() {
            Expr::Lit(Lit::Unit, _) => {
                // return None は省略
            }
            expr => {
                let ret = self.emit_expr(expr);
                self.line(&format!("return {}", ret));
            }
        }
    }
}

// ── Stmt ──────────────────────────────────────────────────────────────────────

impl Emitter {
    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Bind(b) => {
                let val = self.emit_expr(&b.expr);
                match &b.pattern {
                    Pattern::Bind(name, _) if name == "_" => {
                        self.line(&val);
                    }
                    Pattern::Bind(name, _) => {
                        self.line(&format!("{} = {}", name, val));
                    }
                    Pattern::Wildcard(_) => {
                        self.line(&val);
                    }
                    _ => {
                        // 複雑なパターンは _ に落とす
                        self.line(&format!("_ = {}", val));
                    }
                }
            }
            Stmt::Chain(c) => {
                let val = self.emit_expr(&c.expr);
                if c.name == "_" {
                    self.line(&val);
                } else {
                    self.line(&format!("{} = {}", c.name, val));
                }
            }
            Stmt::Expr(e) => {
                let val = self.emit_expr(e);
                self.line(&val);
            }
            Stmt::Yield(y) => {
                let val = self.emit_expr(&y.expr);
                self.line(&format!("yield {}", val));
            }
            Stmt::ForIn(f) => {
                let iter = self.emit_expr(&f.iter);
                self.line(&format!("for {} in {}:", f.var, iter));
                self.indent += 1;
                self.emit_block_body(&f.body);
                self.indent -= 1;
            }
        }
    }
}

// ── Expr ──────────────────────────────────────────────────────────────────────

impl Emitter {
    /// 式を Python 式文字列として返す。
    /// 複雑な変換（helper 関数）が必要な場合は self.buf に先書きして関数呼び出し式を返す。
    fn emit_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Lit(lit, _) => emit_lit(lit),

            Expr::Ident(name, _) => name.clone(),

            Expr::BinOp(op, lhs, rhs, _) => {
                let l = self.emit_expr(lhs);
                let r = self.emit_expr(rhs);
                let py_op = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Eq => "==",
                    BinOp::NotEq => "!=",
                    BinOp::Lt => "<",
                    BinOp::Gt => ">",
                    BinOp::LtEq => "<=",
                    BinOp::GtEq => ">=",
                    BinOp::And => "and",
                    BinOp::Or => "or",
                    BinOp::NullCoalesce => {
                        // `a ?? b` → `(a if a is not None else b)`
                        return format!("({} if {} is not None else {})", l, l, r);
                    }
                };
                format!("({} {} {})", l, py_op, r)
            }

            Expr::Apply(func, args, _) => self.emit_apply(func, args),

            Expr::TypeApply(func, _, _) => self.emit_expr(func),

            Expr::FieldAccess(obj, field, _) => {
                let o = self.emit_expr(obj);
                format!("{}.{}", o, field)
            }

            Expr::If(cond, then_b, else_b, _) => {
                self.emit_if_expr(cond, then_b, else_b.as_deref())
            }

            Expr::Match(scrutinee, arms, _) => self.emit_match_expr(scrutinee, arms),

            Expr::Block(b) => {
                if b.stmts.is_empty() {
                    self.emit_expr(&b.expr)
                } else {
                    self.emit_block_as_helper(b)
                }
            }

            Expr::Closure(params, body, _) => self.emit_closure(params, body),

            Expr::RecordConstruct(ty_name, fields, _) => {
                let args: Vec<String> = fields
                    .iter()
                    .map(|(_, v)| self.emit_expr(v))
                    .collect();
                format!("{}({})", ty_name, args.join(", "))
            }

            Expr::FString(parts, _) => {
                let mut segments: Vec<String> = Vec::new();
                let mut has_expr = false;
                for part in parts {
                    match part {
                        FStringPart::Lit(s) => {
                            segments.push(format!("{:?}", s));
                        }
                        FStringPart::Expr(e) => {
                            has_expr = true;
                            let val = self.emit_expr(e);
                            segments.push(format!("str({})", val));
                        }
                    }
                }
                if has_expr {
                    // f-string 風に + で連結
                    segments.join(" + ")
                } else {
                    segments.join(" + ")
                }
            }

            Expr::Pipeline(exprs, _) => {
                // a |> b |> c → c(b(a))
                if exprs.is_empty() {
                    return "None".to_string();
                }
                let mut parts: Vec<String> =
                    exprs.iter().map(|e| self.emit_expr(e)).collect();
                let mut result = parts.remove(0);
                for func in parts {
                    result = format!("{}({})", func, result);
                }
                result
            }

            Expr::Question(inner, _) => {
                // `expr?` → result unwrap（簡易: そのまま通す）
                let val = self.emit_expr(inner);
                format!("{}_unwrapped", val)
            }

            Expr::Collect(block, _) => {
                // collect { yield x; ... } → list comprehension / helper
                let id = self.next_id();
                let helper = format!("_collect_{}", id);
                let saved_indent = self.indent;
                self.line(&format!("def {}():", helper));
                self.indent += 1;
                self.line("_items = []");
                for stmt in &block.stmts {
                    match stmt {
                        Stmt::Yield(y) => {
                            let val = self.emit_expr(&y.expr);
                            self.line(&format!("_items.append({})", val));
                        }
                        other => self.emit_stmt(other),
                    }
                }
                let tail = self.emit_expr(&block.expr);
                match block.expr.as_ref() {
                    Expr::Lit(Lit::Unit, _) => {}
                    _ => {
                        self.line(&format!("_items.append({})", tail));
                    }
                }
                self.line("return _items");
                self.indent = saved_indent;
                self.blank();
                format!("{}()", helper)
            }

            Expr::AssertMatches(_, _, _) | Expr::EmitExpr(_, _) => {
                "None  # assert/emit not supported in transpile".to_string()
            }
        }
    }

    // ── apply / stdlib 変換 ──────────────────────────────────────────────────

    fn emit_apply(&mut self, func: &Expr, args: &[Expr]) -> String {
        // stdlib 変換: FieldAccess(Ident(ns), method)
        if let Expr::FieldAccess(obj, method, _) = func {
            if let Expr::Ident(ns, _) = obj.as_ref() {
                let a: Vec<String> =
                    args.iter().map(|a| self.emit_expr(a)).collect();
                match (ns.as_str(), method.as_str()) {
                    // ── List ──────────────────────────────────────────────
                    ("List", "empty") => return "[]".to_string(),
                    ("List", "concat") if a.len() == 2 => {
                        return format!("({} + {})", a[0], a[1])
                    }
                    ("List", "length") if a.len() == 1 => {
                        return format!("len({})", a[0])
                    }
                    ("List", "filter") if a.len() == 2 => {
                        return format!("[_x for _x in {} if {}(_x)]", a[0], a[1])
                    }
                    ("List", "map") if a.len() == 2 => {
                        return format!("[{}(_x) for _x in {}]", a[1], a[0])
                    }
                    ("List", "first") if a.len() == 1 => {
                        return format!("({}[0] if {} else None)", a[0], a[0])
                    }
                    ("List", "last") if a.len() == 1 => {
                        return format!("({}[-1] if {} else None)", a[0], a[0])
                    }
                    ("List", "drop") if a.len() == 2 => {
                        return format!("{}[{}:]", a[0], a[1])
                    }
                    ("List", "take") if a.len() == 2 => {
                        return format!("{}[:{}]", a[0], a[1])
                    }
                    ("List", "nth") if a.len() == 2 => {
                        return format!(
                            "({}[{}] if len({}) > {} else None)",
                            a[0], a[1], a[0], a[1]
                        )
                    }
                    ("List", "reverse") if a.len() == 1 => {
                        return format!("list(reversed({}))", a[0])
                    }
                    ("List", "sort") if a.len() == 1 => {
                        return format!("sorted({})", a[0])
                    }
                    ("List", "contains") if a.len() == 2 => {
                        return format!("({} in {})", a[1], a[0])
                    }
                    ("List", "flatten") if a.len() == 1 => {
                        return format!(
                            "[_i for _sub in {} for _i in _sub]",
                            a[0]
                        )
                    }
                    ("List", "zip") if a.len() == 2 => {
                        return format!("list(zip({}, {}))", a[0], a[1])
                    }
                    ("List", "partition") if a.len() == 2 => {
                        return format!(
                            "([_x for _x in {} if {}(_x)], [_x for _x in {} if not {}(_x)])",
                            a[0], a[1], a[0], a[1]
                        )
                    }
                    ("List", "intersperse") if a.len() == 2 => {
                        // [sep].join(lst) — str 前提の近似
                        return format!("{}.join(str(_x) for _x in {})", a[1], a[0]);
                    }
                    ("List", name) => {
                        return format!("_list_{}({})", name, a.join(", "))
                    }

                    // ── String ────────────────────────────────────────────
                    ("String", "concat") if a.len() == 2 => {
                        return format!("({} + {})", a[0], a[1])
                    }
                    ("String", "length") if a.len() == 1 => {
                        return format!("len({})", a[0])
                    }
                    ("String", "trim") if a.len() == 1 => {
                        return format!("{}.strip()", a[0])
                    }
                    ("String", "to_upper") if a.len() == 1 => {
                        return format!("{}.upper()", a[0])
                    }
                    ("String", "to_lower") if a.len() == 1 => {
                        return format!("{}.lower()", a[0])
                    }
                    ("String", "contains") if a.len() == 2 => {
                        return format!("({} in {})", a[1], a[0])
                    }
                    ("String", "starts_with") if a.len() == 2 => {
                        return format!("{}.startswith({})", a[0], a[1])
                    }
                    ("String", "ends_with") if a.len() == 2 => {
                        return format!("{}.endswith({})", a[0], a[1])
                    }
                    ("String", "split") if a.len() == 2 => {
                        return format!("{}.split({})", a[0], a[1])
                    }
                    ("String", "replace") if a.len() == 3 => {
                        return format!("{}.replace({}, {})", a[0], a[1], a[2])
                    }
                    ("String", "join") if a.len() == 2 => {
                        return format!("{}.join({})", a[0], a[1])
                    }
                    ("String", name) => {
                        return format!("_str_{}({})", name, a.join(", "))
                    }

                    // ── Int / Float / Bool 変換 ───────────────────────────
                    ("Int", "to_string") if a.len() == 1 => {
                        return format!("str({})", a[0])
                    }
                    ("Int", "parse") if a.len() == 1 => {
                        return format!("int({})", a[0])
                    }
                    ("Float", "to_string") if a.len() == 1 => {
                        return format!("str({})", a[0])
                    }
                    ("Float", "parse") if a.len() == 1 => {
                        return format!("float({})", a[0])
                    }
                    ("Bool", "to_string") if a.len() == 1 => {
                        return format!("str({}).lower()", a[0])
                    }

                    // ── IO — プレースホルダー（v11.3.0 で実変換）─────────
                    ("IO", "println") if a.len() == 1 => {
                        return format!("print({})", a[0])
                    }
                    ("IO", "print") if a.len() == 1 => {
                        return format!("print({}, end='')", a[0])
                    }
                    ("IO", name) => {
                        return format!("_io_{}({})", name, a.join(", "))
                    }

                    // ── AWS — プレースホルダー（v11.4.0 で実変換）────────
                    ("AWS", name) => {
                        return format!("_aws_{}({})", name, a.join(", "))
                    }

                    // ── Snowflake — プレースホルダー（v11.6.0 以降）──────
                    ("Snowflake", name) => {
                        return format!("_snowflake_{}({})", name, a.join(", "))
                    }

                    // ── Csv / Schema / Json — プレースホルダー ────────────
                    ("Csv", "parse_raw") => {
                        return format!("_csv_parse_raw({})", a.join(", "))
                    }
                    ("Schema", "adapt") => {
                        return format!("_schema_adapt({})", a.join(", "))
                    }
                    ("Schema", "to_json_array") => {
                        return format!("_schema_to_json_array({})", a.join(", "))
                    }
                    ("Json", name) => {
                        return format!("_json_{}({})", name, a.join(", "))
                    }

                    _ => {}
                }
            }
        }

        // 通常の関数呼び出し
        let f = self.emit_expr(func);
        let a: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
        format!("{}({})", f, a.join(", "))
    }

    // ── if 式 ──────────────────────────────────────────────────────────────────

    fn emit_if_expr(
        &mut self,
        cond: &Expr,
        then_b: &Block,
        else_b: Option<&Block>,
    ) -> String {
        let cond_str = self.emit_expr(cond);

        // then / else が単一式のみなら三項式
        let then_simple = then_b.stmts.is_empty();
        let else_simple = else_b.map(|b| b.stmts.is_empty()).unwrap_or(true);

        if then_simple && else_simple {
            let then_val = self.emit_expr(&then_b.expr);
            let else_val = else_b
                .map(|b| self.emit_expr(&b.expr))
                .unwrap_or_else(|| "None".to_string());
            return format!("({} if {} else {})", then_val, cond_str, else_val);
        }

        // 複雑な場合は helper 関数に切り出し
        let id = self.next_id();
        let helper = format!("_cond_{}", id);
        let saved_indent = self.indent;

        self.line(&format!("def {}():", helper));
        self.indent += 1;
        self.line(&format!("if {}:", cond_str));
        self.indent += 1;
        self.emit_block_body(then_b);
        self.indent -= 1;
        if let Some(else_block) = else_b {
            self.line("else:");
            self.indent += 1;
            self.emit_block_body(else_block);
            self.indent -= 1;
        } else {
            self.line("else:");
            self.indent += 1;
            self.line("return None");
            self.indent -= 1;
        }
        self.indent = saved_indent;
        self.blank();

        format!("{}()", helper)
    }

    // ── match 式 ──────────────────────────────────────────────────────────────

    fn emit_match_expr(&mut self, scrutinee: &Expr, arms: &[MatchArm]) -> String {
        let sc = self.emit_expr(scrutinee);

        // Option パターン判定（Some / None のみで構成）
        let is_option_match = arms.iter().all(|a| {
            matches!(
                &a.pattern,
                Pattern::Variant(n, _, _) if n == "Some" || n == "None"
            ) || matches!(&a.pattern, Pattern::Wildcard(_) | Pattern::Bind(_, _))
        }) && arms
            .iter()
            .any(|a| matches!(&a.pattern, Pattern::Variant(n, _, _) if n == "Some" || n == "None"));

        // 全アームが単純式かチェック（stmts なし）
        // match 本体は helper 関数として生成（確実に動作する）
        let id = self.next_id();
        let helper = format!("_match_{}", id);
        let var = format!("_m{}", id);
        let saved_indent = self.indent;

        self.line(&format!("def {}():", helper));
        self.indent += 1;
        self.line(&format!("{} = {}", var, sc));

        let _ = is_option_match; // 将来の最適化用に保持

        for (i, arm) in arms.iter().enumerate() {
            let kw = if i == 0 { "if" } else { "elif" };
            let (cond, bindings) = self.arm_condition(&arm.pattern, &var);
            self.line(&format!("{} {}:", kw, cond));
            self.indent += 1;
            for b in bindings {
                self.line(&b);
            }
            // guard
            if let Some(guard) = &arm.guard {
                let g = self.emit_expr(guard);
                self.line(&format!("if not ({}):", g));
                self.indent += 1;
                // guard 不一致は次アームへスキップ（return None で近似）
                self.line("pass  # guard failed — fall through");
                self.indent -= 1;
            }
            let body = self.emit_expr(&arm.body);
            self.line(&format!("return {}", body));
            self.indent -= 1;
        }
        // デフォルト
        self.line("else:");
        self.indent += 1;
        self.line("return None");
        self.indent -= 1;
        self.indent = saved_indent;
        self.blank();

        format!("{}()", helper)
    }

    fn arm_condition(&self, pat: &Pattern, var: &str) -> (String, Vec<String>) {
        match pat {
            Pattern::Variant(name, inner, _) => match name.as_str() {
                "Some" => {
                    let bind = inner
                        .as_ref()
                        .and_then(|p| extract_bind_name(p))
                        .map(|n| format!("{} = {}", n, var))
                        .into_iter()
                        .collect();
                    (format!("{} is not None", var), bind)
                }
                "None" => (format!("{} is None", var), vec![]),
                "Ok" => {
                    let bind = inner
                        .as_ref()
                        .and_then(|p| extract_bind_name(p))
                        .map(|n| format!("{} = {}.value", n, var))
                        .into_iter()
                        .collect();
                    (format!("isinstance({}, Ok)", var), bind)
                }
                "Err" => {
                    let bind = inner
                        .as_ref()
                        .and_then(|p| extract_bind_name(p))
                        .map(|n| format!("{} = {}.error", n, var))
                        .into_iter()
                        .collect();
                    (format!("isinstance({}, Err)", var), bind)
                }
                other => {
                    let bind: Vec<String> = inner
                        .as_ref()
                        .and_then(|p| extract_bind_name(p))
                        .map(|n| format!("{} = {}.value", n, var))
                        .into_iter()
                        .collect();
                    (format!("isinstance({}, {})", var, other), bind)
                }
            },
            Pattern::Bind(name, _) => {
                // ワイルドカード的バインド — True で束縛
                let bind = if name == "_" {
                    vec![]
                } else {
                    vec![format!("{} = {}", name, var)]
                };
                ("True".to_string(), bind)
            }
            Pattern::Wildcard(_) => ("True".to_string(), vec![]),
            Pattern::Lit(lit, _) => {
                (format!("{} == {}", var, emit_lit(lit)), vec![])
            }
            Pattern::Record(_, _) => {
                ("True  # record pattern".to_string(), vec![])
            }
        }
    }

    // ── Block → helper 関数 ──────────────────────────────────────────────────

    fn emit_block_as_helper(&mut self, block: &Block) -> String {
        let id = self.next_id();
        let helper = format!("_blk_{}", id);
        let saved_indent = self.indent;
        self.line(&format!("def {}():", helper));
        self.indent += 1;
        self.emit_block_body(block);
        self.indent = saved_indent;
        self.blank();
        format!("{}()", helper)
    }

    // ── Closure ──────────────────────────────────────────────────────────────

    fn emit_closure(&mut self, params: &[String], body: &Expr) -> String {
        // 単純な式なら lambda に変換
        let can_lambda = is_simple_expr(body);
        if can_lambda {
            let body_str = self.emit_expr(body);
            let ps = params.join(", ");
            return format!("lambda {}: {}", ps, body_str);
        }
        // 複雑な場合は helper 関数
        let id = self.next_id();
        let helper = format!("_fn_{}", id);
        let saved_indent = self.indent;
        let ps = params.join(", ");
        self.line(&format!("def {}({}):", helper, ps));
        self.indent += 1;
        match body {
            Expr::Block(b) => self.emit_block_body(b),
            other => {
                let val = self.emit_expr(other);
                self.line(&format!("return {}", val));
            }
        }
        self.indent = saved_indent;
        self.blank();
        helper
    }
}

// ── Util ──────────────────────────────────────────────────────────────────────

fn emit_lit(lit: &Lit) -> String {
    match lit {
        Lit::Int(n) => n.to_string(),
        Lit::Float(f) => {
            let s = format!("{}", f);
            if s.contains('.') { s } else { format!("{}.0", s) }
        }
        Lit::Str(s) => format!("{:?}", s),
        Lit::Bool(b) => if *b { "True".to_string() } else { "False".to_string() },
        Lit::Unit => "None".to_string(),
    }
}

fn extract_bind_name(pat: &Pattern) -> Option<String> {
    match pat {
        Pattern::Bind(name, _) if name != "_" => Some(name.clone()),
        _ => None,
    }
}

/// 式が lambda に変換可能な単純式かどうか
fn is_simple_expr(expr: &Expr) -> bool {
    match expr {
        Expr::Lit(_, _) | Expr::Ident(_, _) => true,
        Expr::BinOp(_, l, r, _) => is_simple_expr(l) && is_simple_expr(r),
        Expr::FieldAccess(obj, _, _) => is_simple_expr(obj),
        Expr::Apply(func, args, _) => {
            is_simple_expr(func) && args.iter().all(is_simple_expr)
        }
        _ => false,
    }
}

// ── Tests ──────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod v11100_tests {
    use super::*;

    #[test]
    fn transpile_dataclass_simple() {
        let src = "type Point = {\n  x: Int\n  y: Int\n}";
        let out = emit_python_str(src);
        assert!(out.contains("@dataclass"), "missing @dataclass:\n{}", out);
        assert!(out.contains("class Point:"), "missing class Point:\n{}", out);
        assert!(out.contains("x: int"), "missing x: int:\n{}", out);
        assert!(out.contains("y: int"), "missing y: int:\n{}", out);
    }

    #[test]
    fn transpile_fn_basic() {
        let src = "fn add(a: Int, b: Int) -> Int { a + b }";
        let out = emit_python_str(src);
        assert!(
            out.contains("def add(a: int, b: int) -> int:"),
            "missing def:\n{}",
            out
        );
        assert!(out.contains("return (a + b)"), "missing return:\n{}", out);
    }

    #[test]
    fn transpile_bind_desugars() {
        let src = "fn f(x: Int) -> Int {\n  bind a <- double(x)\n  a\n}";
        let out = emit_python_str(src);
        assert!(out.contains("a = double(x)"), "bind desugaring:\n{}", out);
    }

    #[test]
    fn transpile_match_option() {
        let src = r#"fn f(lst: List<String>) -> String {
  match List.first(lst) {
    Some(v) => v
    None    => ""
  }
}"#;
        let out = emit_python_str(src);
        assert!(
            out.contains("is not None"),
            "Option match Some missing:\n{}",
            out
        );
        assert!(out.contains("is None"), "Option match None missing:\n{}", out);
    }

    #[test]
    fn transpile_match_result() {
        let src = r#"fn f(path: String) -> String {
  match _io_read_file_raw(path) {
    Ok(text) => text
    Err(_)   => ""
  }
}"#;
        let out = emit_python_str(src);
        assert!(
            out.contains("isinstance") && out.contains("Ok"),
            "Result match missing:\n{}",
            out
        );
    }

    #[test]
    fn transpile_list_ops() {
        let src = r#"fn f(lst: List<Int>) -> Int { List.length(lst) }"#;
        let out = emit_python_str(src);
        assert!(out.contains("len(lst)"), "List.length → len():\n{}", out);
    }

    #[test]
    fn transpile_string_concat() {
        let src = r#"fn f(a: String, b: String) -> String { String.concat(a, b) }"#;
        let out = emit_python_str(src);
        assert!(out.contains("(a + b)"), "String.concat → +:\n{}", out);
    }
}
