// fav/src/infer.rs — SAP $metadata URL/ファイルからの型推論（v93.5.0〜）

/// $metadata URL から Favnir 型定義文字列を生成する（v93.5.0 スタブ）
/// 完全実装は v93.8.0 以降（parse_edmx XML 解析完成後）で行う
pub fn infer_from_sap_metadata_url(url: &str) -> String {
    // URL からサービス名を抽出（"/$metadata" を除いた最後のセグメント）
    // strip_suffix を使用して 1 回だけ除去する（trim_end_matches は繰り返し除去するため不使用）
    let trimmed = url.strip_suffix("/$metadata").unwrap_or(url);
    let source = trimmed.rsplit('/').next().unwrap_or("unknown");
    format!(
        "-- Generated by: fav infer --from sap --metadata\n\
         -- Source: {source}\n\
         -- NOTE: parse_edmx is a stub — full XML parsing will be added in v93.8.0+\n"
    )
}

/// ローカルの EDMX ファイルから Favnir 型定義文字列を生成する（v93.6.0 スタブ）
/// 完全実装は v93.8.0 以降（parse_edmx XML 解析完成後）で行う
pub fn infer_from_sap_metadata_file(path: &str) -> String {
    // SAFETY: path はファイルシステムパス（ASCII 前提）のため、バイト境界の問題は発生しない
    format!(
        "-- Generated by: fav infer --from sap --metadata-file\n\
         -- Source: {path}\n\
         -- NOTE: parse_edmx is a stub — full XML parsing will be added in v93.8.0+\n"
    )
}
