#![allow(dead_code)]

//! fav.lock — minimal lock file for reproducible dependency resolution.

use std::path::{Path, PathBuf};

/// A single locked package entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    /// Resolved source path on disk.
    pub resolved_path: String,
    /// Version string (may be empty for path dependencies).
    pub version: String,
}

/// The full lock file.
#[derive(Debug, Clone, Default)]
pub struct LockFile {
    pub packages: Vec<LockedPackage>,
}

impl LockFile {
    pub fn new() -> Self {
        Self { packages: Vec::new() }
    }

    /// Load `fav.lock` from `project_root`. Returns empty lock file if absent.
    pub fn load(project_root: &Path) -> Self {
        let path = project_root.join("fav.lock");
        let Ok(content) = std::fs::read_to_string(&path) else {
            return Self::new();
        };
        parse_lock_file(&content)
    }

    /// Write `fav.lock` to `project_root`.
    pub fn save(&self, project_root: &Path) -> std::io::Result<()> {
        let path = project_root.join("fav.lock");
        let content = self.to_toml();
        std::fs::write(path, content)
    }

    /// Serialize to minimal TOML.
    pub fn to_toml(&self) -> String {
        let mut out = String::from("# fav.lock — generated by `fav install`. Do not edit manually.\n");
        for pkg in &self.packages {
            out.push('\n');
            out.push_str("[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", pkg.name));
            out.push_str(&format!("version = \"{}\"\n", pkg.version));
            out.push_str(&format!("resolved_path = \"{}\"\n", pkg.resolved_path));
        }
        out
    }

    /// Find a locked package by name.
    pub fn get(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| p.name == name)
    }
}

fn parse_lock_file(content: &str) -> LockFile {
    let mut packages = Vec::new();
    let mut cur_name = String::new();
    let mut cur_version = String::new();
    let mut cur_path = String::new();
    let mut in_package = false;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if trimmed == "[[package]]" {
            if in_package && !cur_name.is_empty() {
                packages.push(LockedPackage {
                    name: std::mem::take(&mut cur_name),
                    version: std::mem::take(&mut cur_version),
                    resolved_path: std::mem::take(&mut cur_path),
                });
            }
            in_package = true;
            continue;
        }
        if !in_package {
            continue;
        }
        if let Some((key, val)) = trimmed.split_once('=') {
            let key = key.trim();
            let val = val.trim().trim_matches('"').to_string();
            match key {
                "name"          => cur_name    = val,
                "version"       => cur_version = val,
                "resolved_path" => cur_path    = val,
                _               => {}
            }
        }
    }
    if in_package && !cur_name.is_empty() {
        packages.push(LockedPackage {
            name: cur_name,
            version: cur_version,
            resolved_path: cur_path,
        });
    }
    LockFile { packages }
}

/// Resolve a path dependency relative to the project root.
pub fn resolve_path_dep(project_root: &Path, dep_path: &str) -> PathBuf {
    project_root.join(dep_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lock_file_round_trip() {
        let lock = LockFile {
            packages: vec![
                LockedPackage {
                    name: "mylib".into(),
                    version: "0.1.0".into(),
                    resolved_path: "../mylib".into(),
                },
            ],
        };
        let toml = lock.to_toml();
        let parsed = parse_lock_file(&toml);
        assert_eq!(parsed.packages.len(), 1);
        assert_eq!(parsed.packages[0].name, "mylib");
        assert_eq!(parsed.packages[0].version, "0.1.0");
        assert_eq!(parsed.packages[0].resolved_path, "../mylib");
    }

    #[test]
    fn lock_file_empty_returns_empty() {
        let lock = parse_lock_file("");
        assert!(lock.packages.is_empty());
    }

    #[test]
    fn lock_file_get_finds_package() {
        let lock = LockFile {
            packages: vec![LockedPackage {
                name: "utils".into(),
                version: "1.0.0".into(),
                resolved_path: "/deps/utils".into(),
            }],
        };
        assert!(lock.get("utils").is_some());
        assert!(lock.get("missing").is_none());
    }
}
